fixtures:
  repositories:
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.4.0"
    "staging":
      repo: "git://github.com/nanliu/puppet-staging"
      ref: "1.0.4"
  symlinks:
    "plexmediaserver": "#{source_dir}"
